POST https://api-ujm6kzjyfq-uc.a.run.app/pdf/postage HTTP/1.1
Content-Type: application/json

{
    "xStart": 15.5,
    "yStart": 14,
    "xOffset": 95.5,
    "yOffset": 56,
    "folder": "postage",
    "filename": "j-labels",
    "addresses": [
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom",
        "James Huggins\n54a High Street\nLondon\nSW1 1AA\nWiltshire\nUnited Kingdom"
    ]
} 