POST http://127.0.0.1:5001/tisuk-web/us-central1/api/certificate HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "course": "Diploma in Trauma Informed Schools Test Certificate",
    "date": "2025-05-12",
    "grade": "Merit",
    "filename": "certificate-john-doe.pdf"
}